/**
 * @file telegram-alerts.js
 * @description Telegram bot integration for real-time strategic alerts.
 */

const TELEGRAM_CONFIG = {
    botToken: process.env.TELEGRAM_BOT_TOKEN || '',
    chatId: process.env.TELEGRAM_CHAT_ID || '',
    enabled: process.env.ENABLE_TELEGRAM === 'true'
};

// Rate limiting: max 1 alert per target per hour to prevent spam
const alertHistory = new Map(); // targetId -> lastAlertTime
const ALERT_COOLDOWN = 60 * 60 * 1000; // 1 hour

/**
 * Sends a raw message to the configured Telegram chat.
 */
async function sendTelegramMessage(message, options = {}) {
    if (!TELEGRAM_CONFIG.enabled || !TELEGRAM_CONFIG.botToken || !TELEGRAM_CONFIG.chatId) {
        return { success: false, reason: 'disabled_or_unconfigured' };
    }

    try {
        const url = `https://api.telegram.org/bot${TELEGRAM_CONFIG.botToken}/sendMessage`;
        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                chat_id: TELEGRAM_CONFIG.chatId,
                text: message,
                parse_mode: 'Markdown',
                disable_web_page_preview: true,
                ...options
            })
        });

        const data = await response.json();
        if (!data.ok) {
            console.error('[TELEGRAM] API Error:', data.description);
            return { success: false, reason: data.description };
        }

        return { success: true, messageId: data.result.message_id };
    } catch (error) {
        console.error('[TELEGRAM] Request failed:', error.message);
        return { success: false, reason: error.message };
    }
}

function canSendAlert(targetKey) {
    const lastAlert = alertHistory.get(targetKey);
    if (!lastAlert) return true;
    return (Date.now() - lastAlert) > ALERT_COOLDOWN;
}

function recordAlert(targetKey) {
    alertHistory.set(targetKey, Date.now());
}

/**
 * Sends an alert for a high-value priority target.
 */
async function sendPriorityTargetAlert(asset) {
    const alertKey = `priority-${asset.id}`;
    if (!canSendAlert(alertKey)) return;

    const message = `
🚨 *SENTINEL: STRATEGIC ALERT*
━━━━━━━━━━━━━━━━━━━━━
*Target:* \`${asset.callsign || 'UNKNOWN'}\`
*Type:* ${asset.aircraftType || 'N/A'}
*Hex:* \`${asset.hex || 'N/A'}\`

📍 *Position:*
Lat: \`${asset.lat.toFixed(4)}\`
Lon: \`${asset.lon.toFixed(4)}\`
Alt: \`${asset.altitude} ft\`

⚡ *Telemetry:*
Speed: ${asset.speed} kts
Heading: ${asset.heading}°
Squawk: ${asset.squawk || 'N/A'}

🎯 *Status:* HIGH-VALUE ASSET DETECTED
⏰ *Time:* ${new Date().toISOString()}
━━━━━━━━━━━━━━━━━━━━━
_Generated by SENTINEL OMEGA_
    `.trim();

    const result = await sendTelegramMessage(message);
    if (result.success) recordAlert(alertKey);
    return result;
}

/**
 * Sends an alert for an ADIZ zone incursion.
 */
async function sendADIZAlert(asset, zoneName) {
    const alertKey = `adiz-${asset.id}-${zoneName}`;
    if (!canSendAlert(alertKey)) return;

    const message = `
⚠️ *ADIZ INCURSION DETECTED*
━━━━━━━━━━━━━━━━━━━━━
*Zone:* ${zoneName.toUpperCase()}
*Target:* \`${asset.callsign || asset.hex}\`
*Type:* ${asset.aircraftType || 'N/A'}

📍 *Incursion Point:*
\`${asset.lat.toFixed(4)}, ${asset.lon.toFixed(4)}\`

⏰ *Time:* ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Jakarta' })} WIB
━━━━━━━━━━━━━━━━━━━━━
_Air Defense Monitoring Active_
    `.trim();

    const result = await sendTelegramMessage(message);
    if (result.success) recordAlert(alertKey);
    return result;
}

module.exports = {
    sendTelegramMessage,
    sendPriorityTargetAlert,
    sendADIZAlert,
    TELEGRAM_CONFIG
};
